server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: laptop-service
          uri: lb://laptop-service
          predicates:
            - Path=/laptop/**
        - id: pc-service
          uri: lb://pc-service
          predicates:
            - Path=/pc/**